#!/usr/bin/env node

const chalk = require('chalk')
const args = process.argv

// usage represents the help guide
const usage = function() {
  const usageText = `
  todo helps you manage you todo tasks.

  usage:
    todo <command>

    commands can be:

    add:      used to create a add todo
    ls:      used to retrieve your todos
    done: used to mark a todo as done
    help:     used to print the usage guide
  `

  console.log(usageText)
}

// used to log errors to the console in red color
function errorLog(error) {
  const eLog = chalk.red(error)
  console.log(eLog)
}

// we make sure the length of the arguments is exactly three
if (args.length > 3 && args[2] != 'done') {
  errorLog('only one argument can be accepted')
  usage()
  return
}
const commands = ['add', 'ls', 'done', 'help']
if (commands.indexOf(args[2]) == -1) {
  errorLog('invalid command passed')
  usage()
}

switch(args[2]) {
  case 'help':
    usage()
    break
  case 'add':
    break
  case 'ls':
    break
  case 'done':
    break
  default:
    errorLog('invalid command passed')
    usage()
}

const rl = require('readline');

const low = require('lowdb')
const FileSync = require('lowdb/adapters/FileSync')

const adapter = new FileSync('db.json')
const db = low(adapter)

// Set some defaults (required if your JSON file is empty)
db.defaults({ todos: []}).write()

function prompt(question) {
  const r = rl.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: false
  });
  return new Promise((resolve, error) => {
    r.question(question, answer => {
      r.close()
      resolve(answer)
    });
  })
}

switch(args[2]) {
  //...
  case 'add':
    newTodo()
    break
    // ...
}
function newTodo() {
  const q = chalk.blue("Make your To-Do List:")
  prompt(q).then(todo => {
    db.get('todos')
      .push({
      title: todo,
      done: false
      })
      .write()
  })
}

function getTodos() {
  const todos = db.get('todos').value()
  let index = 1;
  todos.forEach(todo => {
    let todoText = `${index++}. ${todo.title}`
    if (todo.done) {
      todoText += ' ✔' // add a check mark
    }
    console.log(chalk.strikethrough(todoText))
  })
  return
}
//...

// switch statements
switch(args[2]) {
    //...
    case 'ls':
        getTodos()
        break
    case 'done':
        completeTodo()
        break
    //...
}

function completeTodo() {
  // check that length
  if (args.length != 4) {
    errorLog("invalid number of arguments passed for done command")
    return
  }

  let n = Number(args[3])
  // check if the value is a number
  if (isNaN(n)) {
    errorLog("please provide a valid number for done command")
    return
  }

  // check if correct length of values has been passed
  let todosLength = db.get('todos').value().length
  if (n > todosLength) {
    errorLog("invalid number passed for done command.")
    return
  }

  // update the todo item marked as done
  db.set(`todos[${n-1}].done`, true).write()
}
